source 'https://rubygems.org'

gem 'addressable', '~> 2.3'
gem 'byebug', '~> 4.0'
gem 'cucumber', '~> 2.0'
gem 'mixlib-shellout', '~> 2.0'
gem 'page-object', '~> 1.0'
gem 'rake', '~> 10.4'
gem 'require_all', '~> 1.3'
gem 'retriable', '~> 2.0'
gem 'rspec', '~> 3.2'
gem 'watir-webdriver', '~> 0.7'
