source 'https://rubygems.org'

gem 'addressable'
gem 'byebug'
gem 'cucumber'
gem 'mixlib-shellout'
gem 'page-object'
gem 'rake'
gem 'require_all'
gem 'retriable', '~> 2.0'
gem 'rspec'
gem 'watir-webdriver'
